### ISSUE TITLE
ImportError: No module named mediatools_swig

### ISSUE THREAD

**Issue by dyang37** [radioML/dataset#17]
Hi developer,
I was trying to run generate_RML2016.10a.py, and the following run time error occurs:
Mapper warning: Could not load the module “fastcluster”.
The module “scipy.cluster.hierarchy“ is used instead, but it will be slower.
The 'cmappertools' module could not be imported.
The 'cmappertools' module could not be imported.
Intrinsic metric is not available.
The 'cmappertools' module could not be imported.
Traceback (most recent call last):
  File "generate_RML2016.10a.py", line 3, in <module>
    from source_alphabet import source_alphabet
  File "/root/dataset/source_alphabet.py", line 3, in <module>
    import mediatools
  File "/usr/local/lib/python2.7/dist-packages/mediatools/__init__.py", line 45, in <module>
    from mediatools_swig import *
ImportError: No module named mediatools_swig

I have already installed gr-mediatools from source (saw a similar issue there but no response exists). 
Please help.

**Comment by xiexianchao** [comment]
same problem

**Comment by liuzhejun** [comment]
You should install swig first：
`apt install swig`

**Comment by dollshice** [comment]
I have the same problem.Have you solved it now? Can you share it with me?Thank you.
