### ISSUE TITLE
'module' object has no attribute 'audiosource_s'

### ISSUE THREAD

**Issue by Ostnie** [radioML/dataset#23]
I got this error when I run generate_RML2016.10a.py, who can help me, many thanks

Traceback (most recent call last):
  File "generate_RML2016.10a.py", line 42, in <module>
    src = source_alphabet(alphabet_type, tx_len, True)
  File "/home/niejinbo/PycharmProjects/dataset-master/source_alphabet.py", line 35, in __init__
    self.src = mediatools.audiosource_s(["source_material/serial-s01-e01.mp3"])
AttributeError: 'module' object has no attribute 'audiosource_s'

**Comment by GJhaooo** [comment]
Hi, Ostnie!
I have another problem, can you help me? thx!
I can't find the module----"mediatools", where did you get it, could you tell me?
