### ISSUE TITLE
missing submodule dependency

### ISSUE THREAD

**Issue by aapocketz** [radioML/dataset#5]
When running the data generation script, I am missing files

```
source_material/gutenberg_shakespeare.txt: No such file or directory
Traceback (most recent call last):
  File "/home/aaron/src/radioml/dataset/generate_RML2016.10a.py", line 39, in <module>
    src = source_alphabet(alphabet_type, tx_len, True)
  File "/home/aaron/src/radioml/dataset/source_alphabet.py", line 13, in __init__
    self.src = blocks.file_source(gr.sizeof_char, "source_material/gutenberg_shakespeare.txt")
  File "/home/aaron/src/gr/lib/python2.7/dist-packages/gnuradio/blocks/blocks_swig0.py", line 436, in make
    return _blocks_swig0.file_source_make(*args, **kwargs)
RuntimeError: can't open file
```

I do not appear to have access to the dependent submodule.

```

$ git submodule update
Cloning into 'source_material'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:radioML/source_material.git' into submodule path 'source_material' failed

```

Are these files necessary or there is a way to bypass them (use random number generator maybe?)

**Comment by osh** [comment]
http://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules

**Comment by aapocketz** [comment]
I was using submodules properly, I just didn't have access. Running it again worked now. Thanks!

```
 git submodule update
Cloning into 'source_material'...
remote: Counting objects: 4, done.
remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 4
Receiving objects: 100% (4/4), 25.95 MiB | 0 bytes/s, done.
Checking connectivity... done.
Submodule path 'source_material': checked out '07615fff2fe281e9c62a86cd048a3b6cc8bb98db'
```

**Comment by wenfengand** [comment]
```
git@github.com:radioML/source_material.git
```
means it's a clone with ssh. So be sure that you have entered your ssh public key in github

[this page](https://help.github.com/articles/connecting-to-github-with-ssh/) may help.
